trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
  containers:
    - container: mssql
      image: mcr.microsoft.com/mssql/server:2019-latest
      ports:
        - 1433:1433
      env:
        ACCEPT_EULA: Y
        SA_PASSWORD: yourStrong(!)Password

# Service container
services:
  mssql: mssql

steps:
- script: docker network list

- script: |
    network=$(docker network list --filter name=vsts_network -q)
    echo "using $network"
    docker run --rm --network $network mcr.microsoft.com/mssql-tools /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P yourStrong\(!\)Password -Q "SELECT * from sys.databases"
